CREATE TABLE "users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password" VARCHAR(30) NOT NULL UNIQUE,
    "token" CHAR(43) NOT NULL UNIQUE,
    "is_active" BOOLEAN NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_at" TIMESTAMP,
    "last_login" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "idx_user_email" ON "users"("email");


CREATE TABLE "users_phones" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT,
    "country_code" VARCHAR(2) NOT NULL,
    "city_code" VARCHAR(2) NOT NULL,
    "number" VARCHAR(12) NOT NULL,
    CONSTRAINT "fk_phones_users"
        FOREIGN KEY ("user_id")
        REFERENCES "users"("id")
);

CREATE INDEX "idx_users_phones_user_id" ON "users_phones"("user_id");